// Prepares the self-hosted fonts and writes src/styles/fonts.css.
// Usage: node scripts/setup-fonts.mjs
// Why: full CJK fonts are megabytes. FocusList needs Latin text plus a handful of kanji accents,
// so we copy the Latin faces and subset Yuji Syuku down to just those kanji.
import { copyFileSync, mkdirSync, readFileSync, rmSync, writeFileSync, readdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import subsetFont from 'subset-font'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const fontsource = join(root, 'node_modules', '@fontsource')
const outDir = join(root, 'src', 'assets', 'fonts')
rmSync(outDir, { recursive: true, force: true })
mkdirSync(outDir, { recursive: true })

const KANJI = '集中高低済全残'
const LATIN_RANGE =
  'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD'

const latinFaces = [
  { pkg: 'zen-kaku-gothic-new', family: 'Zen Kaku Gothic New', weight: 400 },
  { pkg: 'zen-kaku-gothic-new', family: 'Zen Kaku Gothic New', weight: 500 },
  { pkg: 'zen-kaku-gothic-new', family: 'Zen Kaku Gothic New', weight: 700 },
  { pkg: 'shippori-mincho-b1', family: 'Shippori Mincho B1', weight: 700 },
]

const inRange = (range, codePoint) =>
  range.split(',').some((part) => {
    const [from, to] = part.trim().replace(/^U\+/i, '').split('-')
    const start = parseInt(from, 16)
    const end = to ? parseInt(to, 16) : start
    return codePoint >= start && codePoint <= end
  })

let css = '/* Generated by scripts/setup-fonts.mjs. Only the glyphs FocusList uses. */\n'

for (const { pkg, family, weight } of latinFaces) {
  const file = `${pkg}-latin-${weight}-normal.woff2`
  copyFileSync(join(fontsource, pkg, 'files', file), join(outDir, file))
  css += `@font-face {\n  font-family: '${family}';\n  font-style: normal;\n  font-display: swap;\n  font-weight: ${weight};\n  src: url('../assets/fonts/${file}') format('woff2');\n  unicode-range: ${LATIN_RANGE};\n}\n`
}

const yuji = readFileSync(join(fontsource, 'yuji-syuku', '400.css'), 'utf8')
const blocks = yuji
  .split('@font-face')
  .slice(1)
  .filter((b) => /unicode-range:\s*[^;]+;/.test(b) && /files\/[^)]+\.woff2/.test(b))

const charsBySlice = new Map()
for (const char of KANJI) {
  const codePoint = char.codePointAt(0)
  const block = blocks.find((b) => inRange(b.match(/unicode-range:\s*([^;]+);/)[1], codePoint))
  if (!block) throw new Error(`No Yuji Syuku slice contains ${char}`)
  const file = block.match(/files\/([^)]+\.woff2)/)[1]
  charsBySlice.set(file, (charsBySlice.get(file) ?? '') + char)
}

let index = 0
for (const [file, chars] of charsBySlice) {
  const source = readFileSync(join(fontsource, 'yuji-syuku', 'files', file))
  const subset = await subsetFont(source, chars, { targetFormat: 'woff2' })
  const name = `yuji-syuku-accent-${index++}.woff2`
  writeFileSync(join(outDir, name), subset)
  const range = [...chars].map((c) => `U+${c.codePointAt(0).toString(16).toUpperCase()}`).join(', ')
  css += `@font-face {\n  font-family: 'Yuji Syuku';\n  font-style: normal;\n  font-display: swap;\n  font-weight: 400;\n  src: url('../assets/fonts/${name}') format('woff2');\n  unicode-range: ${range};\n}\n`
}

mkdirSync(join(root, 'src', 'styles'), { recursive: true })
writeFileSync(join(root, 'src', 'styles', 'fonts.css'), css)
const files = readdirSync(outDir)
console.log(`Wrote src/styles/fonts.css: ${latinFaces.length} Latin faces + ${charsBySlice.size} kanji subset(s) (${files.length} files)`)
