// Generated by scripts/build-art.mjs from the Met Open Access API. Do not edit by hand.
import type { Painting } from '../types'
import greatWaveDesktopAvif from '../assets/art/great-wave-desktop.avif'
import greatWaveDesktopWebp from '../assets/art/great-wave-desktop.webp'
import greatWaveMobileAvif from '../assets/art/great-wave-mobile.avif'
import greatWaveMobileWebp from '../assets/art/great-wave-mobile.webp'
import ghostsOfTheTairaDesktopAvif from '../assets/art/ghosts-of-the-taira-desktop.avif'
import ghostsOfTheTairaDesktopWebp from '../assets/art/ghosts-of-the-taira-desktop.webp'
import ghostsOfTheTairaMobileAvif from '../assets/art/ghosts-of-the-taira-mobile.avif'
import ghostsOfTheTairaMobileWebp from '../assets/art/ghosts-of-the-taira-mobile.webp'
import suddenShowerDesktopAvif from '../assets/art/sudden-shower-desktop.avif'
import suddenShowerDesktopWebp from '../assets/art/sudden-shower-desktop.webp'
import suddenShowerMobileAvif from '../assets/art/sudden-shower-mobile.avif'
import suddenShowerMobileWebp from '../assets/art/sudden-shower-mobile.webp'

export const PAINTINGS: Record<'tasks' | 'overview' | 'guide', Painting> = {
  "tasks": {
    id: 45434,
    slug: "great-wave",
    title: "Under the Wave off Kanagawa (Kanagawa oki nami ura), also known as The Great Wave, from the series Thirty-six Views of Mount Fuji (Fugaku sanjūrokkei)",
    artist: "Katsushika Hokusai",
    date: "ca. 1830-32",
    creditLine: "H. O. Havemeyer Collection, Bequest of Mrs. H. O. Havemeyer, 1929",
    objectUrl: "https://www.metmuseum.org/art/collection/search/45434",
    color: "#c0c2b6",
    positionDesktop: "30% 50%",
    positionMobile: "30% 50%",
    desktop: { avif: greatWaveDesktopAvif, webp: greatWaveDesktopWebp, width: 2400, height: 1613 },
    mobile: { avif: greatWaveMobileAvif, webp: greatWaveMobileWebp, width: 900, height: 1600 },
  },
  "overview": {
    id: 55743,
    slug: "ghosts-of-the-taira",
    title: "Ghosts of the Taira at Daimotsu Bay",
    artist: "Utagawa Kuniyoshi",
    date: "1843-47",
    creditLine: "Fletcher Fund, 1929",
    objectUrl: "https://www.metmuseum.org/art/collection/search/55743",
    color: "#6f6d6d",
    positionDesktop: "25% 50%",
    positionMobile: "27% 50%",
    desktop: { avif: ghostsOfTheTairaDesktopAvif, webp: ghostsOfTheTairaDesktopWebp, width: 2400, height: 1181 },
    mobile: { avif: ghostsOfTheTairaMobileAvif, webp: ghostsOfTheTairaMobileWebp, width: 900, height: 1600 },
  },
  "guide": {
    id: 36461,
    slug: "sudden-shower",
    title: "Sudden Shower over Shin-Ōhashi Bridge and Atake (Ōhashi Atake no yūdachi), from the series One Hundred Famous Views of Edo (Meisho Edo hyakkei)",
    artist: "Utagawa Hiroshige",
    date: "1857",
    creditLine: "Purchase, Joseph Pulitzer Bequest, 1918",
    objectUrl: "https://www.metmuseum.org/art/collection/search/36461",
    color: "#939182",
    positionDesktop: "50% 70%",
    positionMobile: "50% 0%",
    desktop: { avif: suddenShowerDesktopAvif, webp: suddenShowerDesktopWebp, width: 1800, height: 1124 },
    mobile: { avif: suddenShowerMobileAvif, webp: suddenShowerMobileWebp, width: 900, height: 1384 },
  },
}
